services:
  - type: web
    name: tiktok-downloader-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: token_bot
        sync: false
      - key: api_id
        sync: false
      - key: api_hash
        sync: false
